### ISSUE TITLE
Do you plan to publish pre-compiled packages

### ISSUE THREAD

**Issue by gpcboekema** [SKalt/geojson-to-wfs-t-2#11]
In order to use your nice library with the create-react-app tool it would be nice if you could add it as pre-compiled package.

See also: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by SKalt** [comment]
Hey @gpcboekema, I can do that.  Transpiling to es5 shouldn't hurt the bundle size of anyone using a module bundler capable of tree-shaking, so I don't have a problem with it.
That said, setting up auto-deployment via travis is my first order of business (see my comments after [issue 9](https://github.com/SKalt/geojson-to-wfs-t-2/issues/9#issuecomment-356648892)).  Eta is a week or so.  If you'd like to add transpilation to the build process, I'll accept a PR so long as it comes with a test.

**Comment by SKalt** [comment]
@gpcboekema : I updated the build process and now you should be able to `import/require` es5 bundles from `gejson-to-wfs-t-2/dist/es5.${format}.js`, where format is one of `umd`, `cjs`, or `es` modules. Let me know if that works.
