### ISSUE TITLE
Support for 3D coordinates

### ISSUE THREAD

**Issue by jessyst** [SKalt/geojson-to-wfs-t-2#12]
While trying to add 3D point to a WFS-T layer I found that you nicely have describe params.srsDimension but it is never passed to the function. 

In the function _translateFeatures_ you use:
_let { srsName } = params;_
that could be (I think):
_let { srsName, srsDimension } = params;_

Then a fewlines down there is:
_fields += xml.tag(ns, geometry_name, {}, geomToGml(feature.geometry, '', { srsName }));_
could be:
_fields += xml.tag(ns, geometry_name, {}, geomToGml(feature.geometry, '', { srsName, srsDimension }));_

Then it would work for points and lines but for the function _Polygon_ I also miss some code:
_'<gml:exterior>' +
        LinearRing(coords[0]) +_
could be:
_'<gml:exterior>' +
        LinearRing(coords[0], gmlId, params) +_

and:
_polygon += '<gml:interior>' + LinearRing(linearRing) + '</gml:interior>';_
could be:
_polygon += '<gml:interior>' + LinearRing(linearRing, gmlId, params) + '</gml:interior>';_

Hope this is of any help.

**Comment by SKalt** [comment]
Good catch, can you give a test case that is causing an issue?  Please feel free to submit a PR with a fix.

**Comment by jessyst** [comment]
I added 2 pull requests

**Comment by jessyst** [comment]
I currently do not have a public WFS-T service so writing a test is difficult but I can give you some examples. The biggest problem is adding 3D points to a 2D layer.
Points will work fine, but lines and polygons will not.

Example:
add to a 2D WFS-T:

<wfs:Transaction xmlns:test="http://www.test.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xsi:schemaLocation="http://www.opengis.net/wfs/2.0
http://schemas.opengis.net/wfs/2.0/wfs.xsd" service="WFS" version="2.0.0">
	<wfs:Insert>
		<test:line2d>
			<test:wkb_geometry>
				<gml:LineString>
					<gml:posList>586090.7408701751 4513228.402903415 -5.828037713649354 586058.7913258693 4513197.812939166 -6.357225025663319 586078.0553597047 4513249.341042338 7.133069927700147</gml:posList>
				</gml:LineString>
			</test:wkb_geometry>
		</test:line2d>
	</wfs:Insert>
</wfs:Transaction>

will result in:

<test:line2d gml:id="line2d.7">
	<test:wkb_geometry>
		<gml:LineString srsName="urn:x-ogc:def:crs:EPSG:26918" srsDimension="2">
			<gml:posList>
586090.74087018 4513228.40290342 -5.82803771 586058.79132587 4513197.81293917 -6.35722503 586078.0553597 4513249.34104234
			</gml:posList>
		</gml:LineString>
	</test:wkb_geometry>
</test:line2d>

add this:

<wfs:Transaction xmlns:test="http://www.test.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xsi:schemaLocation="http://www.opengis.net/wfs/2.0
http://schemas.opengis.net/wfs/2.0/wfs.xsd" service="WFS" version="2.0.0">
	<wfs:Insert>
		<test:line2d>
			<test:wkb_geometry>
				<gml:LineString>
					<gml:posList **srsDimension="3"**>586090.7408701751 4513228.402903415 -5.828037713649354 586058.7913258693 4513197.812939166 -6.357225025663319 586078.0553597047 4513249.341042338 7.133069927700147</gml:posList>
				</gml:LineString>
			</test:wkb_geometry>
		</test:line2d>
	</wfs:Insert>
</wfs:Transaction>

will result in:

<test:line2d gml:id="line2d.8">
	<test:wkb_geometry>
		<gml:LineString srsName="urn:x-ogc:def:crs:EPSG:26918" srsDimension="2">
			<gml:posList>
586090.74087018 4513228.40290342 586058.79132587 4513197.81293917 586078.0553597 4513249.34104234
			</gml:posList>
		</gml:LineString>
	</test:wkb_geometry>
</test:line2d>

The mapserver will understand to ignore the z-value when you add srsDimension="3"

**Comment by SKalt** [comment]
closed in #13
