### ISSUE TITLE
Transaction generation does not ensure XML-safe strings

### ISSUE THREAD

**Issue by PizzaBrandon** [SKalt/geojson-to-wfs-t-2#14]
The library does not currently generate XML-safe strings from raw inputs.

1. Insert a feature with a property `name` and value `A & B`.
2. Generate transaction.

Expected in XML: `<name>A &amp; B</name>`

Actual in XML: `<name>A & B</name>`

This can be accomplished by a workaround by the consumer, but may be something the library should do (with major semver bump as to not break consumers who are already handling this).

**Comment by PizzaBrandon** [comment]
Would you be opposed to replacing the manual XML generation with a popular, supported XML generation library?

**Comment by SKalt** [comment]
I wouldn't, so long as it is slim and generates strings.

**Comment by PizzaBrandon** [comment]
I guess I'll hold off on that, then. My preferred xml builder utility isn't small, but it's quite comprehensive. Side-effect would be a potential change to the gml library, too. I'll just put together a small drop-in.

**Comment by SKalt** [comment]
Hmm, content validation is a good issue for the gml lib.

You might get away with a content escaping  function like `c =>
c.replace('&', '&amp;').replace ('<', ...).replace('>', ...)`. Is this what
you were thinking of / see any problems with that strategy?

**Comment by PizzaBrandon** [comment]
Yeah, that's essentially what I was going to do. I was going to do it in `xml.tag`, but it won't be safe to do there because it allows passing in XML and not just raw values. Barring a larger refactor, the xml escaping will have to be done where the attributes and values are read.

**Comment by SKalt** [comment]
xml.js is the right file for it. How about exporting the function and
importing and using it within attribute reading in Insert and  Update?
Something like `wfs.tag('Property', {...}, xml.escape(content))`

**Comment by PizzaBrandon** [comment]
Yes, I'm creating an `xml.escape`. I was referring to just applying the escaping directly in `xml.tag`, which won't work for us.

**Comment by SKalt** [comment]
Makes sense; thanks for taking this on.

**Comment by PizzaBrandon** [comment]
The overall scope of the fix grew a bit in order to get the build and tests working after modularization. Hope to have a PR early next week. Sorry for the delay.

**Comment by PizzaBrandon** [comment]
I finally got approval to submit my PR. It will come from a different repo than before, but I should have it submitted within a couple days. Thanks!
