### ISSUE TITLE
NPM package not reflecting XML.escape

### ISSUE THREAD

**Issue by PizzaBrandon** [SKalt/geojson-to-wfs-t-2#18]
Can you verify the correct code was built and published to NPM? I just looked at 1.3.3 and 1.3.4 and neither of them were deployed with the new XML.escape function.

**Comment by SKalt** [comment]
Turns out the updated files were not being `git add`ed before versioning and publication.

**Comment by SKalt** [comment]
to test: 
```{bash}
mkdir temp-test
cd temp-test
npm i geojson-to-wfs-t-2
cat ./node_modules/geojson-to-wfs-t-2/dist/es5.cjs.js | grep escape
```

**Comment by PizzaBrandon** [comment]
I can confirm 1.4.0 has the XML escaping code. Thanks!
