### ISSUE TITLE
Short question regarding Update(features, params)

### ISSUE THREAD

**Issue by TobiTobsen92** [SKalt/geojson-to-wfs-t-2#2]
The `Update(features, params)` method expects the `params` object to have a `geometry`-property assigned to it when a property `geometry_name` is provided. Simply calling the method with a feature and some parameters (including, amongst other things, a `geometry_name` property) does not work since usually only the feature is holding its geometry. The respective code snippet is as follows:
```
if (geometry_name) {
      fields += xml.tag(ns, geometry_name, {}, geomToGml(params.geometry, '', { srsName }));
   }
```
Each time I'm using the function I need to manually assign the feature's `geometry` property to the `params` object in order to make it generate my wfs update request correctly. Why does the method expect the `params` object to have a property `geometry` if a parameter `geometry_name` is provided? Is there something I'm missing about the correct usage of the method? I would very much appreciate a short answer to this, since the library generally saves me a lot of work :)

**Comment by SKalt** [comment]
My original thinking was, if you want to update the geometries of a batch
of features, you can't be sure which feature.geometry you should use for
the update.

I'd be interested in alternate syntax, like:
... geomToGml( params.geometry || (features[0]||{}).geometry)

**Comment by TobiTobsen92** [comment]
Thank you for your fast reply! So copying the feature's `geometry` attribute to the `params` object is the intended way of use?

**Comment by SKalt** [comment]
Yep, I wanted it to be explicit that an update is applied all input
features. I'll let you know if I go ahead with a refactor to allow an
update(singleFeature, {geometry_name}) using the feature's geometry.
Similarly, feel free to shoot me a PR.

**Comment by TobiTobsen92** [comment]
Okay thanks, now it's a bit clearer to me!
