### ISSUE TITLE
Publish 1.5.0?

### ISSUE THREAD

**Issue by PizzaBrandon** [SKalt/geojson-to-wfs-t-2#20]
I noticed NPM still shows 1.4.0 as the latest but the repo has been updated to 1.5.0. Does this need to be published?

**Comment by SKalt** [comment]
Looks like it does.  I'll only be able to get to that over the weekend, unfortunately.
I've been meaning to rebase to add a changelong to the release tags, so we'll see how that goes.

**Comment by PizzaBrandon** [comment]
Appears v1.5.0 has the same breaking issue that previous versions have, for anyone running Node 6:

```
.../geojson-to-wfs-t-2/dist/es6.cjs.js:208
  return Object.entries(obj).map(([type, converter]) => {
                ^

TypeError: Object.entries is not a function```

I'm not sure how it wasn't included in the latest build. The code this references appears to be coming in from `geojson-to-gml-3.2.1` (makeConverter). Would you be opposed to either trading out `entries` for a `keys(obj).forEach` or importing corejs into the other plugin?

**Comment by SKalt** [comment]
This is tough.  On one hand, I strongly prefer writing ESNext (`Object.entries` seems to be ES 2017).  On the other, swapping `forEach` is a pretty small fix.
While I waffle on this, here are some fixes for you and anyone writing using a [maintenance node LTS](https://github.com/nodejs/Release#release-schedule):
- grab the ES5 backwards compatibility version I included in `dist` a while back
- `npm i` parcel or webpack 4, both of which should support transpiling modern ES out-of-the-box to umd/cjs/*.

**Comment by SKalt** [comment]
Another thought: polyfilling
```
Object.entries = Object.entries || function(obj) {
   const keys = Object.keys(obj);
   return keys.map((key) => [key, obj[key]]);
}
```
Placing this before you `require('geojson-to-wfs-t-2')` is probably the easiest patch.

**Comment by SKalt** [comment]
Hey @PizzaBrandon  I replaced the manual polyfills with `@babel/env` in 1.5.1, which may have inadvertently included the Object.entries polyfill. Whether it did or not, I'm interested in closing this issue.

**Comment by PizzaBrandon** [comment]
We moved to node 8 a while back, in part to pick up this change, so this hasn't been an issue for us. I think it's good practice to make sure a library supports all LTS versions of node. Node 6 goes end-of-life in April.
