### ISSUE TITLE
Strict MIME type checking error

### ISSUE THREAD

**Issue by ivder** [SKalt/geojson-to-wfs-t-2#29]
Hi I install the program using npm 
`npm install geojson-to-wfs-t-2`

But I got an error when importing the library using
`import wfs from '../node_modules/geojson-to-wfs-t-2';`

It produces an error on the browser
`Strict MIME type checking is enforced for module scripts per HTML spec.`

![image](https://user-images.githubusercontent.com/32887298/75131978-8e82f480-5718-11ea-8e94-d86d3948a020.png)

**Comment by SKalt** [comment]
Hey, the mime type error indicates you're improperly serving the module.  I'm not going to walk you through how to serve an ES6 module from node_modules, but I will recommend using parcel-bundler to get started.
