### ISSUE TITLE
Please publish latest version to NPM

### ISSUE THREAD

**Issue by PizzaBrandon** [SKalt/geojson-to-wfs-t-2#5]
I ran across a bug in the version on NPM and noticed it was fixed in the version in this repo. Can you please publish the latest version to NPM? Thanks!

**Comment by SKalt** [comment]
Done; let me know if it works.

**Comment by PizzaBrandon** [comment]
Thank you for updating, but that version doesn't work. The `package.json` is pointing to `geojson-to-wfst-cjs.js` but the file's name is `geojson-to-wfst-2-cjs.js`

**Comment by PizzaBrandon** [comment]
Other than that, the bug I was experiencing is corrected. Thank you!

**Comment by SKalt** [comment]
I shot out a fix for this here and on npm.  I've got to work now, but
please let me know if you hit any more snags.

**Comment by PizzaBrandon** [comment]
This version works straight from NPM. Thank you!
