### ISSUE TITLE
Enable support for `lockId` and `releaseAction` in Transaction

### ISSUE THREAD

**Issue by PizzaBrandon** [SKalt/geojson-to-wfs-t-2#7]
As I was using the library, I noticed that `lockId` and `releaseAction` are listed as possible params to Transaction, but they are not being used.

**Comment by PizzaBrandon** [comment]
In case you are interested in accepting the change, I have submitted a PR for your approval. If you do approve this change, I would appreciate it if you would publish it to NPM so I can return to using the official version rather than my clone. Thanks!

**Comment by SKalt** [comment]
Republished.  Worth warning you, I have several changes in the works: 

1.  I'm certain I want to break the utility functions out of the main module for readability
2.  I'm considering refactoring the action functions (Transaction, Insert, etc) either to lowercase or to es6 classes.
