### ISSUE TITLE
False-y properties are not added to XML

### ISSUE THREAD

**Issue by PizzaBrandon** [SKalt/geojson-to-wfs-t-2#9]
My colleague discovered a bug in the library when attempting to send a property with value `false` through, but noticed it wasn't in the transaction XML. I think I've identified the bug location: [Line 110: `properties[prop] ? cb(prop, properties[prop]) : pass();`](https://github.com/SKalt/geojson-to-wfs-t-2/blob/master/geojson-to-wfst-2-es6.js#L110)

This will pass over any false-y property value: `null`, `undefined`, `0`, `false`, `''`, etc. Since there are cases where any of these values may be desired, with the exception of `undefined`, should this be changed to strictly check whether the value is undefined and then represent the other values in the XML?

**Comment by SKalt** [comment]
Yep. Patch it, add a test case, and I'll merge and publish tonight.

**Comment by PizzaBrandon** [comment]
Thanks! We'll get started on developing the fix. I suspect it will be larger in scope since it has trickle-down effects into the XML generation code. I don't have a timeline for correction, but we'll PR it as soon as we have it working.

**Comment by PizzaBrandon** [comment]
I'm finishing up the patch now. Do you mind if I remove the "No gmlId supplied" warning? We see it consistently as our code runs.

**Comment by PizzaBrandon** [comment]
Never mind about `gmlId`, I guess that's coming from the other package.

**Comment by SKalt** [comment]
Thanks for the contrib! I'll see about purging the gmlId message from [the gml converter](https://github.com/SKalt/geojson-to-gml-3.2.1/blob/master/geomToGml-3.2.1-es6.js#L41).

**Comment by PizzaBrandon** [comment]
Thanks for the merge! If you are satisfied with the change, can you publish it to NPM?

**Comment by SKalt** [comment]
Published.  I'm currently fighting through a flu and interview season, but expect the gml warning squashed and travis->nmp deployment set up in around a week.

**Comment by PizzaBrandon** [comment]
No worries about the message, it's not impacting the servers, just adding to the logs. Care for yourself first and get better soon!
